# Generated by Django 5.2.4 on 2025-07-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_city_commune_contree_projetcontribution_contribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='id_transaction',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribution',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contribution',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
