# Generated by Django 5.2.4 on 2025-07-15 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contribution_id_transaction_contribution_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetcontribution',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city'),
        ),
    ]
