# Generated by Django 5.2.4 on 2025-07-16 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_projetcontribution_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetcontribution',
            name='montant_recolte',
        ),
    ]
