# Generated by Django 5.2.4 on 2025-07-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_projetcontribution_montant_recolte'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetcontribution',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_projets_contribution/'),
        ),
        migrations.AddField(
            model_name='projetrealise',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_projets/'),
        ),
    ]
