# Generated by Django 5.2.4 on 2025-07-17 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_projetcontribution_video_projetrealise_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetrealise',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city'),
        ),
    ]
