# Generated by Django 5.2.4 on 2025-07-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_projetrealise_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='contree',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='ville',
        ),
    ]
